# Generated by Django 3.2.9 on 2021-12-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='yt_link',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
    ]
